version: "3"
services:
  app:
    build: ./docker_flask
    volumes:
      - ./docker_flask/app:/app
      - socket:/tmp
    command: uwsgi --ini /app/app.ini
  web:
    image: nginx:latest
    ports:
      - "8090:80"
    volumes:
      - ./docker_flask/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - socket:/tmp

volumes:
  socket: